packages:
  - 'apps/*'
  - 'packages/*'
  - 'packages/parsers/*'

catalog:
  typescript: ^5.9.3
  eslint: ^10.0.1
  '@eslint/js': ^10.0.1
  typescript-eslint: ^8.56.0
  eslint-plugin-svelte: ^3.15.0
  eslint-config-prettier: ^10.1.8
  svelte-eslint-parser: ^1.4.1
  globals: ^17.3.0
  prettier: ^3.8.1
  prettier-plugin-svelte: ^3.4.1
  turbo: ^2.8.10
  vitest: ^4.0.18
  '@types/node': ^25.3.0
  zod: ^4.3.6
