packages:
  - 'apps/*'
  - 'packages/*'
  - 'packages/parsers/*'

catalog:
  typescript: ^5.9.3
  eslint: ^10.0.2
  '@eslint/js': ^10.0.1
  typescript-eslint: ^8.56.1
  eslint-plugin-svelte: ^3.15.0
  eslint-config-prettier: ^10.1.8
  svelte-eslint-parser: ^1.5.1
  globals: ^17.3.0
  prettier: ^3.8.1
  prettier-plugin-svelte: ^3.5.0
  turbo: ^2.8.12
  vitest: ^4.0.18
  '@types/node': ^25.3.3
  zod: ^4.3.6
  svelte: ^5.53.6
  '@sveltejs/kit': ^2.53.4
  '@sveltejs/adapter-node': ^5.5.4
  '@tailwindcss/vite': ^4.2.1
  tailwindcss: ^4.2.1
  svelte-check: ^4.4.4
  vite: ^7.3.1
  clsx: ^2.1.1
  tailwind-merge: ^3.5.0
  tailwind-variants: 3.2.2
  tw-animate-css: 1.4.0
  '@internationalized/date': ^3.11.0
  '@lucide/svelte': 0.575.0
  bits-ui: ^2.16.2
  mode-watcher: ^1.1.0
  drizzle-orm: ^0.45.1
  drizzle-kit: ^0.31.9
  postgres: ^3.4.8
  dotenv: ^17.3.1
  tsx: ^4.19.4
  fast-xml-parser: ^5.4.1
  bullmq: ^5.70.1
  ioredis: ^5.10.0
  pino: ^10.3.1
